<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php if ($this->session->has('auth')) { ?>

<div class="page-header" align="center">
    <h1>
        Search part
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["part/new", "Add part"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "part/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPartnumber" class="col-sm-5 control-label">Part Number</label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(["partnumber", "size" => 30, "class" => "form-control", "id" => "fieldPartnumber"]) ?>
    </div>
    <div class="col-sm-3"></div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-5 control-label">Description</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["description", "size" => 30, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
    <div class="col-sm-3"></div>
</div>

<div class="form-group">
    <div class="col-sm-offset-5 col-sm-7">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<?php } else { ?>

    You must log back in to continue...

<?php } ?>
