<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php if ($this->session->has('auth')) { ?>

<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
        <nav>
            <ul class="pager">
                <li class="previous"><?php echo $this->tag->linkTo(["part/index", "Go Back"]); ?></li>
                <li class="next"><?php echo $this->tag->linkTo(["part/new", "Create "]); ?></li>
            </ul>
        </nav>
    </div>
    <div class="col-sm-1"></div>
</div>

<div class="page-header" align="center">
    <h1>Part search results</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
        <table class="table table-bordered">
            <thead>
                <tr>
                <th>Part Number</th>
                <th>Description</th>
                <th>On Hand</th>
                <th>Min</th>
                <th>Max</th>

                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $part): ?>
                <tr>
                <td><?php echo $part->partnumber ?></td>
                <td><?php echo $part->description ?></td>
                <td><?php echo $part->onhand ?></td>
                <td><?php echo $part->min ?></td>
                <td><?php echo $part->max ?></td>

                    <td><?php echo $this->tag->linkTo(["part/edit/" . $part->id, "Edit"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["part/delete/" . $part->id, "Delete"]); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="col-sm-1"></div>
</div>

<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-10">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("part/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("part/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("part/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("part/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>

<?php } else { ?>

    You must log back in to continue...

<?php } ?>