<?php use Phalcon\Tag as Tag ?>

<html>
    <head>
        <title>GreenLeaf IMS</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="\greenleafMVC\public\css\bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style type="text/css"></style>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/greenleafMVC/alerts/index">GreenLeaf IMS</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
<?php if ($this->session->has('auth')) { ?>
                	    <li> <?php echo Phalcon\Tag::linkTo('alerts/index', 'Alerts') ?> </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Record Sales<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li> <?php echo Phalcon\Tag::linkTo('Sales/index', 'Part Sales') ?> </li>
                                    <li class="divider"></li>
                                    <li> <?php echo Phalcon\Tag::linkTo('Sales/salesnozzle', 'Nozzle Sales') ?> </li>
                                </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Inventory<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li> <?php echo Phalcon\Tag::linkTo('inventory/receive', 'Receive Parts') ?> </li>
                                    <li> <?php echo Phalcon\Tag::linkTo('inventory/adjust', 'Part Adjustment') ?> </li>
                                    <li class="divider"></li>
                                    <li> <?php echo Phalcon\Tag::linkTo('inventory/ordernozzles', 'Order Nozzles') ?> </li>
                                    <li> <?php echo Phalcon\Tag::linkTo('inventory/receivenozzle', 'Receive Nozzles') ?> </li>
                                    <li> <?php echo Phalcon\Tag::linkTo('inventory/adjustn', 'Nozzle Adjustment') ?> </li>
                                </ul>
                        </li>
                        <li> <?php echo Phalcon\Tag::linkTo('reports/index', 'Reports') ?> </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Admin<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li> <?php echo Phalcon\Tag::linkTo('part/new', 'Add Parts') ?> </li>
                                    <li> <?php echo Phalcon\Tag::linkTo('part/index', 'Edit Parts') ?> </li>
                                    <li class="divider"></li>
                                    <li> <?php echo Phalcon\Tag::linkTo('nozzle/new', 'Add Nozzles') ?> </li>
                                    <li> <?php echo Phalcon\Tag::linkTo('nozzle/index', 'Edit Nozzles') ?> </li>

                                    

                                </ul>
                        </li>
                        <li> <?php echo Phalcon\Tag::linkTo('users/logout', 'Sign out') ?> </li>

<?php } ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"></a></li>
                    </ul>
                </div>
            </div>
        </nav>

<?php echo $this->getContent() ?>
    </body>
</html>
