<div class="page-header" align="center">
    <h1>Open Contractor Jobs</h1>
</div>

<?php if ($this->session->has('auth')) { ?>

<div class="container-fluid">
        <div class="row">
            <div class="col-sm-2" style="background-color:white;"></div>
            <div class="col-sm-1" style="background-color:white;">
                <label class="control-label" for="login">Job#</label>
            </div>
            <div class="col-sm-3" style="background-color:white;">
                <label class="control-label" for="login">Contractor</label>
            </div>
            <div class="col-sm-1" style="background-color:white;">
                <label class="control-label" for="login">Due</label>
            </div>
            <div class="col-sm-5" style="background-color:white;"></div>
        </div><br>

<div class="container-fluid">
        <div class="row">
            <div class="col-sm-2" style="background-color:white;"></div>
            <div class="col-sm-2" style="background-color:white;">
            No Open Jobs
            </div>
            <div class="col-sm-8" style="background-color:white;"></div>
        </div>

<?php } else { ?>

    <li>

        You must log back in to continue...

    </li>

<?php } ?>