<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php if ($this->session->has('auth')) { ?>

    <div class="page-header" align="center">
        <h1>
            Record Nozzle Sale
        </h1>
    </div>

    <?php echo $this->getContent(); ?>

    <?php
    echo $this->tag->form(
        [
            "sales/recordnozzle",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
    ?>


    <div class="form-group">
        <label for="fieldPartnumber" class="col-sm-5 control-label">Part Number</label>
        <div class="col-sm-3">
            <?php echo $this->tag->textField(["partnum", "size" => 30, "class" => "form-control", "id" => "fieldPartnumber"]) ?>
        </div>
        <div class="col-sm-2"></div>
    </div>

    <div class="form-group">
        <label for="fieldQty" class="col-sm-5 control-label">Qty</label>
        <div class="col-sm-2">
            <?php echo $this->tag->textField(["qty", "size" => 30, "class" => "form-control", "id" => "fieldQty"]) ?>
        </div>
        <div class="col-sm-5"></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-7">
            <?php echo $this->tag->submitButton(["Record", "class" => "btn btn-default"]) ?>
        </div>
    </div>

    <?php echo $this->tag->endForm(); ?>

<?php } else { ?>

    You must log back in to continue...

<?php } ?>
