<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php if ($this->session->has('auth')) { ?>

<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
        <nav>
            <ul class="pager">
                <li class="previous"><?php echo $this->tag->linkTo(["customer", "Search"]) ?></li>
            </ul>
        </nav>
    </div>
    <div class="col-sm-1"></div>
</div>

<div class="page-header" align="center">
    <h1>
        Create customer
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "customer/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-5 control-label">Name</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
    <div class="col-sm-4"></div>
</div>


<div class="form-group">
    <div class="col-sm-offset-5 col-sm-7">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<?php } else { ?>

    You must log back in to continue...

<?php } ?>